feat: get version from tag

diff --git a/.github/workflows/pypi-publish-on-release.yml b/.github/workflows/pypi-publish-on-release.yml
--- a/.github/workflows/pypi-publish-on-release.yml
+++ b/.github/workflows/pypi-publish-on-release.yml
@@ -6,8 +6,15 @@ on:
       - published
 
 jobs:
+  call-test-lint:
+    uses: ./.github/workflows/test-lint.yml
+    with:
+      ref: ${{ github.event.release.target_commitish }}
+
   build:
     name: Build distribution 📦
+    needs:
+      - call-test-lint
     runs-on: ubuntu-latest
 
     steps:
@@ -24,6 +31,17 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install hatch twine
+
+    - name: Validate version
+      run: |
+        version=$(hatch version)
+        if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Valid version format"
+            exit 0
+        else
+            echo "Invalid version format"
+            exit 1
+        fi
 
     - name: Build
       run: |
@@ -44,8 +62,8 @@ jobs:
     # environment is used by PyPI Trusted Publisher and is strongly encouraged
     # https://docs.pypi.org/trusted-publishers/adding-a-publisher/
     environment:
-      name: testpypi
-      url: https://test.pypi.org/p/strands-agents
+      name: pypi
+      url: https://pypi.org/p/strands-agents
     permissions:
       # IMPORTANT: this permission is mandatory for Trusted Publishing
       id-token: write
@@ -56,8 +74,5 @@ jobs:
       with:
         name: python-package-distributions
         path: dist/
-
-    - name: Publish distribution 📦 to TestPyPI
+    - name: Publish distribution 📦 to PyPI
       uses: pypa/gh-action-pypi-publish@release/v1
-      with:
-        repository-url: https://test.pypi.org/legacy/
